      - name: Commit Updated Deals

        run: |

          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"

          # HARD RESET
          git reset --hard

          # CLEAN FILES
          git clean -fd

          # FETCH LATEST
          git pull origin main --rebase

          # ADD FILES
          git add .

          # COMMIT
          git commit -m "auto update deals" || echo "No changes"

          # PUSH
          git push origin main
