name: Telegram Deal Bot

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:

  workflow_dispatch:

  schedule:
    - cron: '* * * * *'

jobs:

  run-bot:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # =============================================
      # CHECKOUT
      # =============================================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # =============================================
      # PYTHON
      # =============================================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # =============================================
      # INSTALL REQUIREMENTS
      # =============================================

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      # =============================================
      # RUN BOT
      # =============================================

      - name: Run Telegram Fetcher

        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STR: ${{ secrets.SESSION_STR }}

        run: |
          python -u backend/telegram_bot.py

      # =============================================
      # COMMIT CHANGES
      # =============================================

      - name: Commit Updated Deals

        run: |

          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"

          git add .

          git commit -m "auto update deals" || echo "No changes"

          git pull --rebase origin main || true

          git push || true
